name: Build and Push Go Backend Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up commit hash
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t prajapati003/ai_frontend:${{ env.SHORT_SHA }} .

      - name: List Docker Images
        run: docker images

      - name: Push Docker Image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push prajapati003/ai_frontend:${{ env.SHORT_SHA }}
