name: Build and Push Go Backend Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Determine Docker Tag
        id: set_tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAG=prod-${GITHUB_SHA::8}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "TAG=staging-${GITHUB_SHA::8}" >> $GITHUB_ENV
          else
            echo "TAG=dev-${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t prajapati003/ai_frontend:${{ env.TAG }} .

      - name: List Docker Images
        run: docker images

      - name: Push Docker Image to Docker Hub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          docker push prajapati003/ai_frontend:${{ env.TAG }}

